# Generated by Django 2.1.3 on 2018-11-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0002_auto_20181110_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(default=''),
        ),
    ]
